const EVENTS = {
    STACK_PUSH_FRAME: 'STACK_PUSH_FRAME',
    STACK_POP_FRAME: 'STACK_POP_FRAME',
    ROUTER_ROUTE_CHANGE: 'ROUTER_ROUTE_CHANGE',
    ROUTER_ROUTE_ADD: 'ROUTER_ROUTE_ADD',
}

export { EVENTS }
